is_train: False
is_select: True
test_model_path: "/content/for checking better results/_epoch_50.pkl"
embed_units: 300
symbols: 30000
units: 512
layers: 2
batch_size: 16
data_dir: "data"
num_epoch: 50
lr_rate: 0.0001
lstm_dropout: 0.3
linear_dropout: 0.2
max_gradient_norm: 5
trans_units: 100
gnn_layers: 3
fact_dropout: 0.0
fact_scale: 1
pagerank_lambda: 0.8
result_dir_name: "sort output"
generated_path: "for checking better results"